### ISSUE TITLE
Make LuckPerms optional

### ISSUE THREAD

**Issue by piebaker** [Dreaming-Codes/DiscordLoom#1]
I use the awesome [player roles ](https://modrinth.com/mod/player-roles) mod, but i really would like to use the discord auth / whitelist features. It would be awesome if luckperms was a (recommended) but optional module for this mod!

**Comment by Dreaming-Codes** [comment]
Thanks for your interest and suggestion! However, I'm sorry to inform you that it isn't possible to make Luckperms an optional module for this mod without major rewrite. This is because I use Luckperms metakey to store the discord ID, which is essential to this mod's functionality.

However, if you are interested in contributing, I'm open to collaborations. If you would like to open a Pull Request (PR) for it, you're more than welcome to do so! Your contributions would be highly appreciated.
